openapi: 3.0.3
info:
  title: Payment Service API
  description: REST API to create payments (debit) with asynchronous Kafka notification via outbox.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/payments:
    post:
      summary: Create a payment (debit)
      operationId: createPayment
      parameters:
        - $ref: '#/components/parameters/XUserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
            example:
              accountId: "11111111-1111-1111-1111-111111111111"
              amount: 80.00
              currency: "CHF"
              paymentId: "3fa85f64-5717-4562-b3fc-2c963f66afa9"
      responses:
        '200':
          description: Payment processed successfully (notification will be sent asynchronously)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                paymentId: "3fa85f64-5717-4562-b3fc-2c963f66afa9"
                status: "COMPLETED"

        '400':
          description: Validation error (missing/invalid fields) or missing/invalid header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "VALIDATION_ERROR"
                message: "amount must be positive"
                timestamp: "2026-01-13T12:00:00Z"

        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "ACCOUNT_NOT_FOUND"
                message: "Account not found"
                timestamp: "2026-01-13T12:00:00Z"

        '403':
          description: Account not owned by user / forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "FORBIDDEN"
                message: "Account not owned by user"
                timestamp: "2026-01-13T12:00:00Z"

        '409':
          description: Duplicate payment (idempotency conflict)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "DUPLICATE_PAYMENT"
                message: "Duplicate payment request detected"
                timestamp: "2026-01-13T12:00:00Z"

        '422':
          description: Insufficient funds
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "INSUFFICIENT_FUNDS"
                message: "Insufficient funds"
                timestamp: "2026-01-13T12:00:00Z"

        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "INTERNAL_ERROR"
                message: "Unexpected error occurred"
                timestamp: "2026-01-13T12:00:00Z"

components:
  parameters:
    XUserId:
      name: X-User-Id
      in: header
      required: true
      description: Simulated authenticated user id (UUID).
      schema:
        type: string
        format: uuid
      example: "22222222-2222-2222-2222-222222222222"

  schemas:
    PaymentRequest:
      type: object
      required:
        - accountId
        - amount
        - currency
        - paymentId
      properties:
        accountId:
          type: string
          format: uuid
          description: ID of the account to debit
          example: "11111111-1111-1111-1111-111111111111"
        amount:
          type: number
          description: Amount to debit (must be positive)
          example: 80.00
        currency:
          type: string
          description: Currency code (e.g., CHF, USD)
          example: "CHF"
        paymentId:
          type: string
          format: uuid
          description: Idempotency key / unique payment identifier (used for deduplication)
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa9"
      additionalProperties: false
      example:
        accountId: "11111111-1111-1111-1111-111111111111"
        amount: 80.00
        currency: "CHF"
        paymentId: "3fa85f64-5717-4562-b3fc-2c963f66afa9"

    PaymentResponse:
      type: object
      required:
        - paymentId
        - status
      properties:
        paymentId:
          type: string
          format: uuid
          description: Payment id (same value as request.paymentId for idempotency)
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa9"
        status:
          type: string
          description: Payment status
          example: "COMPLETED"
      additionalProperties: false

    ErrorResponse:
      type: object
      required:
        - code
        - message
        - timestamp
      properties:
        code:
          type: string
          description: Error code
          example: "INSUFFICIENT_FUNDS"
        message:
          type: string
          description: Human-readable error message
          example: "Insufficient funds"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
      additionalProperties: false
